"""
UMAP Dimensionality Reduction for CLIP Embeddings.

This script takes the 512-dimensional CLIP embeddings generated by vectorise.py
and reduces them to 2D coordinates using UMAP. The output can be directly
used for scatter plot visualisation.

Author: Rashid
Supervisor: XinHui Ma
Project: Visualising Natural Disaster Image Embeddings
"""

import sys
import numpy as np
import umap
import json
from pathlib import Path
from datetime import datetime
from typing import Tuple, List, Optional


# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import config


# Paths
EMBEDDINGS_PATH = PROJECT_ROOT / "data" / "embeddings" / "embeddings.npy"
FILENAMES_PATH = PROJECT_ROOT / "data" / "embeddings" / "filenames.json"
OUTPUT_DIR = PROJECT_ROOT / "data" / "visualisation"


def load_embeddings() -> Tuple[Optional[np.ndarray], Optional[List[str]]]:
    """Load the CLIP embeddings from disk.
    
    Returns:
        Tuple of (embeddings array, filenames list) or (None, None) if not found.
    """
    
    print("Loading embeddings from: {}".format(EMBEDDINGS_PATH))
    
    if not EMBEDDINGS_PATH.exists():
        print("Embeddings file not found")
        print("Please run vectorise.py first to generate embeddings")
        
        
        return None, None
    
    embeddings = np.load(EMBEDDINGS_PATH)
    print("Loaded {} embeddings of dimension {}".format(embeddings.shape[0], embeddings.shape[1]))
    
    
    # Load filenames if available
    filenames = None
    if FILENAMES_PATH.exists():
        
        with open(FILENAMES_PATH, "r") as f:
            filenames = json.load(f)
            
        print("Loaded {} filenames".format(len(filenames)))
    
    return embeddings, filenames


def run_umap(embeddings: np.ndarray) -> np.ndarray:
    """
    Apply UMAP dimensionality reduction.
    
    Args:
        embeddings: Array of shape (N, 512).
        
    Returns:
        Array of shape (N, 2) containing 2D coordinates.
    """
    
    print("Running UMAP reduction")
    print("n_neighbors: {}".format(config.UMAP_N_NEIGHBOURS))
    print("min_dist: {}".format(config.UMAP_MIN_DIST))
    print("metric: {}".format(config.UMAP_METRIC))
    
    start_time = datetime.now()
    
    reducer = umap.UMAP(
        n_neighbors=config.UMAP_N_NEIGHBOURS,
        min_dist=config.UMAP_MIN_DIST,
        n_components=config.UMAP_N_COMPONENTS,
        metric=config.UMAP_METRIC,
        random_state=config.UMAP_RANDOM_STATE,
        verbose=True
    )
    
    coords = reducer.fit_transform(embeddings)
    
    elapsed = datetime.now() - start_time
    print("UMAP complete in {}".format(elapsed))
    
    return coords


def save_results(coords: np.ndarray, filenames: Optional[List[str]]) -> None:
    """Save the 2D coordinates to disk.
    
    Args:
        coords: 2D UMAP coordinates of shape (N, 2).
        filenames: Optional list of source filenames.
    """
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Save coordinates as numpy array
    coords_path = OUTPUT_DIR / "umap_coords.npy"
    np.save(coords_path, coords)
    
    print("Saved coordinates to: {}".format(coords_path))
    print("Shape: {}".format(coords.shape))
    
    # Save as JSON for the demo app (x, y, path format)
    umap_data = []
    
    for i, (x, y) in enumerate(coords):
        entry = {
            "x": float(x),
            "y": float(y),
            "path": filenames[i] if filenames else str(i)
        }
        
        umap_data.append(entry)
    
    json_path = OUTPUT_DIR / "umap_data.json"
    
    with open(json_path, "w") as f:
        json.dump(umap_data, f, indent=2)
        
    print("Saved JSON data to: {}".format(json_path))
    
    # Save metadata
    
    metadata = {
        "generated_at": datetime.now().isoformat(),
        "n_samples": len(coords),
        "n_neighbors": config.UMAP_N_NEIGHBOURS,
        "min_dist": config.UMAP_MIN_DIST,
        "metric": config.UMAP_METRIC,
        "random_state": config.UMAP_RANDOM_STATE
    }
    
    metadata_path = OUTPUT_DIR / "umap_metadata.json"
    
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
        
    print("Saved metadata to: {}".format(metadata_path))
    
    # Copy filenames for convenience
    if filenames:
        filenames_path = OUTPUT_DIR / "filenames.json"

        with open(filenames_path, "w") as f:
            json.dump(filenames, f, indent=2)

        print("Copied filenames to: {}".format(filenames_path))


def main():
    """Main entry point."""
    
    print("Starting UMAP Reduction")
    print("Timestamp: {}".format(datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
    
    # Load embeddings
    embeddings, filenames = load_embeddings()
    
    if embeddings is None:
        sys.exit(1)
    
    # Run UMAP
    coords = run_umap(embeddings)
    
    # Save the results
    save_results(coords, filenames)
    
    print("Pipeline complete.")


if __name__ == "__main__":
    main()
