name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda with Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: .github/workflows/environment.yml
        use-mamba: true
        auto-activate-base: false

    - name: Conda Cache
      uses: actions/cache@v4
      with:
        path: /usr/share/miniconda/pkgs
        key: conda-${{ runner.os }}-${{ hashFiles('.github/workflows/environment.yml') }}

    - name: Verify Conda Environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda run -n my-research-env python --version

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda run -n my-research-env flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n my-research-env flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda run -n my-research-env pytest
